# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{term_extractor}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rattle"]
  s.date = %q{2010-12-23}
  s.email = %q{robl[at]rjlee.net}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/term_extractor.rb",
    "term_extractor.gemspec",
    "test/test_helper.rb",
    "test/test_term_extractor.rb"
  ]
  s.homepage = %q{}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provides term extraction functionality}
  s.test_files = [
    "test/test_helper.rb",
    "test/test_term_extractor.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rbtagger>, [">= 0.0.0"])
    else
      s.add_dependency(%q<rbtagger>, [">= 0.0.0"])
    end
  else
    s.add_dependency(%q<rbtagger>, [">= 0.0.0"])
  end
end

